version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensor
      MYSQL_USER: mydb
      MYSQL_PASSWORD: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # Mensajería AMQP
      - "15672:15672" # UI de administración

  api1:
    build:
      context: ./cmd/api1 # El contexto es la raíz del proyecto, ya que tu Dockerfile está ahí
      dockerfile: Dockerfile.api1
    container_name: api1
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DB_HOST: mysql
      DB_USER: mydb
      DB_PASSWORD: mydb
      DB_NAME: mydb
      RABBITUSER: guest
      RABBITPASSWORD: guest
      RABBITIP: rabbitmq
      RABBITPORT: 5672
    ports:
      - "8080:8080"

volumes:
  mysql_data:
