# Usar la imagen base de Go
FROM golang:1.23

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar go.mod y go.sum al contenedor
COPY ./go.mod ./go.sum ./

# Descargar las dependencias
RUN go mod tidy

# Copiar todo el código fuente del proyecto al contenedor
COPY . .

# Construir la aplicación
RUN go build -o /app/api2 main.go

# Ejecutar la aplicación
CMD ["/app/api2"]
